name: FoliaChallenges
version: 1.0
author: dinu_shay
main: foliachallenges.FoliaChallengePlugin
api-version: 1.21
description: A challenge plugin for Folia servers
folia-supported: true
commands:
  challenges:
    description: Manage the challenge timer
  timer:
    description: Manage the challenge timer (alias for /challenges)
  start:
    description: Start the timer
    usage: /<command>
  reset:
    description: Reset the world
    usage: /<command> <confirm>
  settings:
    description: Open the settings GUI
    usage: /<command>
