name: FoliaChallenges
version: 1.0
author: dinu_shay
main: foliachallenges.FoliaChallengePlugin
api-version: 1.21
description: A challenge plugin for Folia servers
folia-supported: true
commands:
  challenges:
    description: Manage the challenge timer
    aliases: [challenge]
  timer:
    description: Manage the challenge timer (alias for /challenges)
  resume:
    description: Resume the challenge timer
  start:
    description: Start the timer
    usage: /<command>
  reset:
    description: Löscht alle Daten und die Welt!
    usage: /reset confirm
    permission: foliachallenges.reset
